export enum COMMAND_TYPES {
  START_SESSION = 'START_SESSION',
  STOP_SESSION = 'STOP_SESSION',
  WRITE_STDIN = 'WRITE_STDIN',
  WRITE_STDOUT = 'WRITE_STDOUT',
  ERROR = 'ERROR',
  SHUTDOWN = 'SHUTDOWN'
}
